### ISSUE TITLE
[Connection Issue]: Can commission but then goes offline

### ISSUE THREAD

**Issue by a-y-m-a-n** [t0bst4r/home-assistant-matter-hub#308]
### Version

:latest

### Matter Controller

Google Home

### Things you tried

I setup matter hub in a docker container, ipv6 enabled, able to bring up the browser to the ipv6 addy.  I scan the code and commission (setup a minimal 1 lightbulb hub).  I can see the entity update in the matter hub browser but can't see/control from google home.  When I do commission it sometimes I have to try it twice, but it usually goes through right away on the 2nd try.

I do have VLANs but in this case everything is on the same subnet (I have some esphome devices on a separate network but that isn't the case for this hub)

I setup debug logging and see lots of curious messages but not sure how to interpret -- this is a snippit

`[ 2024-12-15T07:20:46.613Z ] [ DEBUG ] [ WebApi / Access Log                                ]: GET /api/matter/bridges/6c72851d95e643daa26dfc12e45dbe3b/devices?_s=1734247246604 404 Not Found from ::ffff:192.168.37.102
[ 2024-12-15T07:20:52.647Z ] [ DEBUG ] [ Matter / DeviceAdvertiser                          ]: Announcement duration reached, stop announcing
[ 2024-12-15T07:20:56.609Z ] [ DEBUG ] [ WebApi / Access Log                                ]: GET /api/matter/bridges/6c72851d95e643daa26dfc12e45dbe3b/devices?_s=1734247256601 404 Not Found from ::ffff:192.168.37.102
[ 2024-12-15T07:20:57.580Z ] [ DEBUG ] [ Matter / MdnsScanner                               ]: Adding operational device 8655D494A4D273FD-000000005C300D18._matter._tcp.local in cache (interface ens32, ttl=120) with TXT data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
`

 I do see this on the browser (edge) occasionally:

`Unexpected token 'N', "Not Found" is not valid JSON  and I can click the x and it just repeats for 10 or so and after some time I see it again.
`

Not sure what else to try ... thanks

### Relevant log output

```shell
[ 2024-12-15T07:20:46.613Z ] [ DEBUG ] [ WebApi / Access Log                                ]: GET /api/matter/bridges/6c72851d95e643daa26dfc12e45dbe3b/devices?_s=1734247246604 404 Not Found from ::ffff:192.168.37.102
[ 2024-12-15T07:20:52.647Z ] [ DEBUG ] [ Matter / DeviceAdvertiser                          ]: Announcement duration reached, stop announcing
[ 2024-12-15T07:20:56.609Z ] [ DEBUG ] [ WebApi / Access Log                                ]: GET /api/matter/bridges/6c72851d95e643daa26dfc12e45dbe3b/devices?_s=1734247256601 404 Not Found from ::ffff:192.168.37.102
[ 2024-12-15T07:20:57.580Z ] [ DEBUG ] [ Matter / MdnsScanner                               ]: Adding operational device 8655D494A4D273FD-000000005C300D18._matter._tcp.local in cache (interface ens32, ttl=120) with TXT data: SII: 500 SAI: 300 SAT: 4000 T: 0 DT: undefined PH: undefined ICD: 0 VP: undefined DN: undefined RI: undefined PI: undefined
```

### What deployment method do you use?

Docker

### Did you already check the following?

- [X] Does your network include any VLAN setup?
- [X] Do you have any special firewall rules / services in place?
- [X] Is IPv6 enabled in your LOCAL network?
- [X] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [X] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
```
[ 2024-12-15T07:20:46.613Z ] [ DEBUG ] [ WebApi / Access Log                                ]: GET /api/matter/bridges/6c72851d95e643daa26dfc12e45dbe3b/devices?_s=1734247246604 404 Not Found from ::ffff:192.168.37.102
```

When you are at the bridge-details page in the frontend, it updates the list of devices every 10 seconds.
Somehow you have at least one browser tab open for a bridge with id `6c72851d95e643daa26dfc12e45dbe3b`. But this bridge does not exist anymore. It's not related to the other lines of the log.

---

```
Unexpected token 'N', "Not Found" is not valid JSON
```

This is more or less a bug. When the backend returns 404 Not Found (previous topic) the frontend tries to parse it as a json, which is simply wrong. Anyway this only happens because the requested bridge is not existing.

---

>  I scan the code and commission (setup a minimal 1 lightbulb hub). I can see the entity update in the matter hub browser but can't see/control from google home.

This is your original issue. So let me get this right:
- you can commission with google home
- you can see all your devices in google home
- they won't update when changed from HA
- they appear offline in GH
- you cannot control them from GH

Right?

We have seen that issue before, when IPv6 or VLANs or Firewalls weren't setup 100% correct.
Make sure that port 5353 and the port of the bridge (most likely 5540) are allowed with UDP.
Make sure that Google Home and HAMH can communicate via IPv6.
Make sure that Docker is configured correctly to allow IPv6 communication.
Make sure that GH and HAMH are in the same VLAN segment / subnet.

**Comment by a-y-m-a-n** [comment]
> 
> This is your original issue. So let me get this right:
> 
> * you can commission with google home
Yes
> * you can see all your devices in google home
Yes, well the only 1 I added I see
> * they won't update when changed from HA
In the Matter browser, they do update as expected  -- but not in GH
> * they appear offline in GH
Correct
> * you cannot control them from GH
Correct

> 
> We have seen that issue before, when IPv6 or VLANs or Firewalls weren't setup 100% correct. Make sure that port 5353 and the port of the bridge (most likely 5540) are allowed with UDP. Make sure that Google Home and HAMH can communicate via IPv6. Make sure that Docker is configured correctly to allow IPv6 communication. Make sure that GH and HAMH are in the same VLAN segment / subnet.

That was my instinct too that it is something with ipv6 and docker -- but i will try to validate the rest as well.  The host is dual honed but I can't point to that as an issue yet.  One thing I would like to know:  Is there some simple equivalent to GH that I can run on linux to help debug where the connection is failing?

Thanks so much -- awesome work.

**Comment by Schwippser** [comment]
i have the same issue ... 
- i can commision with GH
- i see all devices in GH, but all devices and matter-hub are offline in GH
- new labeled device not added to GH

- if i commision the same matter-hub to matter-server-addon in HA everything works and i can control devices via Matter-Integration in HA

**Comment by a-y-m-a-n** [comment]
Ok, so in my specific case, what I figured out so far -- 

i have two physical machines running Debian 12, one is my HA machine with lots of docker containers, the other is my development machine.  

Both same lan, subnets, etc.  BUT only my dev machine is able to get ipv6 via dhcp6 and slaac from pfsense.  The HA machine cannot -- i have no idea why.   Running dhclient -6 -d eth0 never shows any responses from pfsense.  ping6 obviously won't work, etc.  That is what I am trying to figure out now.  Localhost ipv6 works but not sure what to conclude from that yet.

So that is where I am at.  But it tells me that for whatever reason I can commission w/o ipv6 functional -- that surprised me.

**Comment by Schwippser** [comment]
i have HA running in a Proxmox VM. I can see the HA IPv6 in the network-overview of my router.
i also have a HA-test-machine. i will run a test tomorrow

**Comment by Schwippser** [comment]
i have tested today with a laptop running HA OS directly at my router. I was running into the same issue. I can commission the matter-hub and i see the babeled device in GH. But matter-hub and the devices are shown as offline.
What's surprising is that it worked once 4 days ago. Without changing anything, it hasn't worked since then. I've run out of ideas.

**Comment by a-y-m-a-n** [comment]
Ok, so I solved my issue and as I suspected it was something to do w/ the ipv6.   This is definitely specific to my setup:    On my physical lan I have a pfsense router with 8 ports.  1 is upstream WAN and the rest  are unused or LAN ports.  What I found is that there is some specific configuration needed to bridge ipv6 over bridged LAN ports in pfsense, at least the DHCP6 and RA need something it appears.  What something is, I don't know.  I solved it by redoing my physical port assignments so that all the ipv6 stuff is on a regular gige switch -- other stuff (such as my Hue bridge) can hang off one of the bridged ports fine.  And now it works.  Thanks!

**Comment by Schwippser** [comment]
I also fixed my issue. What can I say... the problem was in front of the screen. I moved my GoogleDot last weekend and didn't plug the power cable back in properly. Now everything is working again.

**Comment by KamilKeenan** [comment]
I still have a similar problem. My HAOS runs on a laptop connected via ehternet cable to the router (it has ipv6 enabled). when I add MatterHub to G-Home devices show up correctly but they go offline after short time. What is interesting that it works flawlessly with Apple Home on my wife's Iphone. any idea what may be the issue? 🙏

**Comment by drstil** [comment]
I am running HAOS with Matter Hub add-on on a Raspberry Pi 5 which is connected via LAN to a FRITZBox. Google Home Mini is connected via WLAN and my iPhone with Google Home App also in the same WLAN (FRITZBox). IPV6 is enabled in the network. I can ping6 all devices. 
Devices in Google Home App have always been offline, never online. Readded Matter Hub and Bridge many times. Also devices (Raspberry, Router, Google Nest Mini, iPhone) have been restarted many times.
